name: Deploy to S3 AWS

on:
  push:
    branches:
      - Full-Stack-Project-mesgna-woldeab

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install AWS CLI
        run: |
          sudo apt-get install -y awscli

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.REGION }}

      - name: Sync client/build to S3 bucket
        run: aws s3 sync ~/OneDrive/Documents/CFY/Full-Stack-Project-Assessment/client/build/ s3://video-recommendation-2024
