---
services:
  - type: web
    plan: free
    name: video-recommendation
    region: frankfurt
    env: node
    buildCommand: npm ci --include dev; npm run build; npm prune --omit dev
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: video-recommendation-db
          property: connectionString
      - key: NODE_ENV
        value: production

databases:
  - name: video-recommendation-db
    region: frankfurt
    databaseName: cyf
    plan: free
    ipAllowList: [] # only allow internal connections
