CREATE TABLE urls (id SERIAL PRIMARY KEY, title VARCHAR(50), url VARCHAR(50), rating INTEGER );
INSERT INTO urls(id,title,url,rating) VALUES (523523,'Never','https://www.youtube.com/watch?v=dQw4w9WgXcQ',3500);
INSERT INTO urls(id,title,url,rating) VALUES (523427,'The Coding Train','https://www.youtube.com/watch?v=HerCR8bw_GE',230);
INSERT INTO urls(id,title,url,rating) VALUES (82653,'Mac & Cheese ','https://www.youtube.com/watch?v=FUeyrEN14Rk',2111);
INSERT INTO urls(id,title,url,rating) VALUES (858566,'Videos for Cats','https://www.youtube.com/watch?v=Dh-ULbQmmF8',11);
INSERT INTO urls(id,title,url,rating) VALUES (453538,'Chris Brown Soul','https://www.youtube.com/watch?v=dnIiFIddJLo',3211);
INSERT INTO urls(id,title,url,rating) VALUES (283634,'Coding Adventure','https://www.youtube.com/watch?v=U4ogK0MIzqk',211);
INSERT INTO urls(id,title,url,rating) VALUES (562824,'The Let Out','https://www.youtube.com/watch?v=JWIqrKhP2Kg',111);
INSERT INTO urls(id,title,url,rating) VALUES (442452,'Tia Tamera','https://www.youtube.com/watch?v=C_yI2959DYU',671);
INSERT INTO urls(id,title,url,rating) VALUES (536363,'Imma Get It','https://www.youtube.com/watch?v=6b6K1Umz_ro',76);