export const SET_VIDEOS = 'SET_VIDEOS';

// export const VIDEO_UP_VOTE = 'VIDEO_UP_VOTE';
// export const VIDEO_DOWN_VOTE = 'VIDEO_DOWN_VOTE';

// export const VIDEO_TO_DELETE = 'VIDEO_TO_DELETE';
export const VIDEO_SUCCESSFULLY_DELETED = 'VIDEO_SUCCESSFULLY_DELETED';

export const VIDEO_SUCCESSFULLY_ADDED = 'VIDEO_SUCCESSFULLY_ADDED';

export const VIDEO_VOTING_SUCCESSFUL = 'VIDEO_VOTING_SUCCESSFUL';
