export const SET_VIDEOS = 'SET_VIDEOS';

export const VIDEO_UP_VOTE = 'VIDEO_UP_VOTE';
export const VIDEO_DOWN_VOTE = 'VIDEO_DOWN_VOTE';

export const VIDEO_VOTING_SUCCESSFUL = 'VIDEO_VOTING_SUCCESSFUL';
