name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup and run tests
        working-directory: ./client
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      
      - run: ls
      - run: npm install
      - run: npm run build --if-present
      - run: npm test
