
name: Deploy

on:
  push:
    branches: [ fullstack-final ]

jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@v2
      - run: ls
      - name: Build & Deploy
        env:
          PRIVATE_KEY: ${{ secrets.SSH_EC2_SECRET }}
          HOSTNAME: ${{ secrets.SSH_HOST }}
          USER_NAME: ${{ secrets.SSH_USERNAME }}
        shell: bash
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME}

        
