name: EC2 Deploy

on:
  push:
    branches:
      - "*"
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create private key
        run: echo "${{ secrets.MY_SECRET_SSH_KEY}}" > secretKey.pem

      - name: Connect to EC2
        run: |
         - name: Rsync files to EC2
  run: rsync -avz --exclude=node_modules --exclude=.env -e "ssh -i secretKey.pem -o StrictHostKeyChecking=no" ./ ec2-user@ec2-18-171-148-184.eu-west-2.compute.amazonaws.com:~/project/Full-Stack-Project-Assessment/server/
