name: Deploy to EC2

on:
 push:
    branches:
      - Level--300

jobs:
 deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
         host: ${{ secrets.HOST_DNS }}
         username: ${{ secrets.USERNAME }}
         key: ${{ secrets.EC2_SSH_KEY }}
         script: |
          cd server
          git pull origin master
          sudo systemctl restart server.js
       
         
