name: Deploy backend to EC2
on:
 push:
  branches: Level--300 
  
jobs:
 Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2 
      - name: Build & Deploy
        env:
            PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            HOSTNAME: ${{secrets.HOST_NAME}}
            USER_NAME: ${{secrets.USER_NAME}}
  
 
