name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js and npm
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install Dependencies
        run: |
          npm install

      - name: Debug SSH Key and Directory
        run: |
          echo "SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}"
          mkdir -p $HOME/.ssh/
          echo "SSH key content: ${{ secrets.SSH_PRIVATE_KEY }}" > $HOME/.ssh/id_rsa
          chmod 600 $HOME/.ssh/id_rsa
          ls -l $HOME/.ssh/
          cat $HOME/.ssh/id_rsa

      - name: Update Known Hosts
        run: |
          ssh-keyscan -t rsa,ed25519 ec2-13-42-39-111.eu-west-2.compute.amazonaws.com >> $HOME/.ssh/known_hosts


      - name: Rsync to EC2
        run: |
          rsync -avz --exclude 'node_modules' --exclude '.git' --exclude '.env' \
            -e "ssh -i $HOME/.ssh/id_rsa" \
            /path/to/source ubuntu@ec2-13-42-39-111.eu-west-2.compute.amazonaws.com:/path/to/destination

      - name: Build
        run: |
          npm run build

      - name: Install systemd
        run: |
          sudo systemctl daemon-reload
          sudo systemctl enable myapp.service
          sudo systemctl start myapp.service

      - name: Run systemd
        run: |
          sudo systemctl daemon-reload
          sudo systemctl enable myapp.service  
          sudo systemctl start myapp.service   
