name: Deploy to EC2

on:
  push:
    branches:
      - Level--300

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push docker image  
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags:  harounalarabi/server:latest

    - name: Deploy to EC2
      uses: easingthemes/ssh-deploy@v2.1.4
      with:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        ARGS: "-avz --delete"
        SOURCE: "server/"
        REMOTE_HOST: ${{ secrets.HOST_DNS }}
        REMOTE_USER: ${{ secrets.USERNAME }}
        TARGET: "/home/ubuntu/server"
