name: Deploying to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository//download the source code repository
        uses: actions/checkout@v2

      - name: Use Node.js 16
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Configure AWS credentials// AWS credentials are configuring
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install dependencies and build
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{secrets.AWS_PEM}} "${{secrets.AWS_HOST_NAME}}@${{secrets.AWS_HOST}}"
              cd Full-Stack-Project-Assessment
              git pull
              cd server
              npm install
              pm2 restart server.js
