name: Deploy to EC2

on:
 push:
    branches:
      - Level--300
jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the files
      uses: actions/checkout@v2

    - name: Build and Test
      run: |
       cd server
      
    - name: Deploy to EC2
      uses: easingthemes/ssh-deploy@main
      env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          SSH_CMD_ARGS: "-o StrictHostKeyChecking=no"
      with:
          run: |
           cd server

