name: Deploy to EC2

on:
  push:
    branches:
      - Level--300

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the files
      uses: actions/checkout@v2

    - name: Build and Test
      run: |
        # Add your build and test commands here

    - name: Remove Previous Deployment
      uses: easingthemes/ssh-deploy@main
      with:
        REMOTE_HOST: ${{ secrets.HOST_DNS }}
        REMOTE_USER: ${{ secrets.USERNAME }}
        REMOTE_PORT:  22
        ARGS: "-avz --delete"
        
        
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}

    - name: Deploy to EC2
      uses: easingthemes/ssh-deploy@main
      with:
        local-path: server
        ARGS: "-avz"
        TARGET: "/home/ubuntu"
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        REMOTE_HOST: ${{ secrets.HOST_DNS }}
        REMOTE_USER: ${{ secrets.USERNAME }}
