name: Deploy to EC2

on:
 push:
    branches:
      - Level--300
jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the files
      uses: actions/checkout@v2

    - name: Build and Test
      run: |
       
    - name: Remove Previous Deployment
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        REMOTE_HOST: ${{ secrets.HOST_DNS }}
        REMOTE_USER: ${{ secrets.USERNAME }}
        REMOTE_PORT: 22
        REMOTE_SCRIPT: 'rm -rf /home/ubuntu/'
        
    - name: Deploy to EC2
      uses: easingthemes/ssh-deploy@main
      with:
       local-path: server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        REMOTE_HOST: ${{ secrets.HOST_DNS }}
        REMOTE_USER: ${{ secrets.USERNAME }}
      
       
         
