name: Deploying to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository//download the source code repository
        uses: actions/checkout@v3

      - name: Create private key
        run: echo "${{ secrets.AWS_PEM}}" > myPlayList-key-pair.pem

      - name: Update PATH
        run: |
          set PATH=$PATH:/home/ubuntu/.nvm/versions/node/v20.11.1/bin/pm2

      - name: Install dependencies and build
        run: |
          chmod 400 myPlayList-key-pair.pem
          echo "${{vars.AWS_HOST_NAME}}@${{vars.AWS_HOST}}"
          cat myPlayList-key-pair.pem
          ssh -i myPlayList-key-pair.pem -o StrictHostKeyChecking=no ${{vars.AWS_HOST_NAME}}@${{vars.AWS_HOST}} '
              source .bashrc
              cd Full-Stack-Project-Assessment &&
              pwd &&
              git pull &&
              cd server &&
              pm2 restart server.js
              '
