name: Deploy backend to EC2
on:
 [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_NAME }}
          username: ${{ secrets.USER_NAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd server
            npm install
            npm build
            npm i serve
            serve -p 3000 build
              
 
