name: Deploy

on:
  push:
    branches: main

jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2 

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '19.x'

      - name: Build & Deploy
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOSTNAME: ${{ secrets.HOST_DNS }}
          USER_NAME: ${{ secrets.USERNAME }}
      
        run: |
          echo "$PRIVATE_KEY" > private_key
          chmod 600 private_key
          
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
              # Now we have got the access of EC2 and we will start the deploy.
              cd /home/ubuntu/video-app
              sudo npm i &&
              sudo systemctl daemon-reload &&
              sudo systemctl enable myapp.service &&
              sudo systemctl start myapp.service
          '
