name: Deploy Backend

on:
  push:
    branches: main
  pull_request:
    branches: main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [19.x]

    steps:
      - uses: actions/checkout@v3

      - run: npm ci
      - run: npm run build
      - run: npm run test

      - name: rsync deployments
        uses: aws-actions/configure-aws-credentials@v1
        with:
          switches: -avzr --delete
          path: ./*
          remote_path: /var/www/video-app/
          remote_host: http://ec2-13-42-39-111.eu-west-2.compute.amazonaws.com
          remote_user: ubuntu
          remote_key: "${{ secrets.SSH_PRIVATE_KEY }}"