
name: Deploy

on:
  push:
    branches: [ fullstack-final ]

jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2 
      - name: Deploy to my EC2 instance
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_EC2_SECRET }}
          SOURCE: "./"
          REMOTE_HOST: "ec2-13-40-127-171.eu-west-2.compute.amazonaws.com"
          REMOTE_USER: "ubuntu"
          TARGET: "/home/ec2-user/SampleExpressApp"
              
