name: Deploy to EC2

on:
  push:
    paths:
      - "server/**"
    branches:
      - "*"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Prepare the environment
        run: npm install

      - name: Deploy to EC2
        run: |
          rsync -avz --exclude=node_modules --exclude=.env -e "ssh -i C:\Users\mesgn\OneDrive\Desktop\mesgna.pem" ./ ubuntu@ip-172-31-24-164:~/project/Full-Stack-Project-Assessment/server$ 
