name: Node.js Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 12

      - name: Check Existing Directory
        run: |
          if [ -d "$HOME/.video-app" ]; then
            echo "Directory already exists."
          else
            mkdir $HOME/.video-app
          fi

      - name: Install Dependencies
        run: npm install

      - name: rsync deployments
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: -avzr --delete
          path: ./server
          remote_path: /home/ubuntu
          remote_host: ${{  secrets.AWS_HOST }}
          remote_port: 22
          remote_user: ${{ secrets.USERNAME}}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
     