name: Deploying to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository//download the source code repository
        uses: actions/checkout@v2
        env:
          HOST_NAME: ${{secrets.AWS_HOST_NAME}}
          AWS_HOST: ${{secrets.AWS_HOST}}
          PEM: ${{secrets.AWS_PEM}}

      - name: Install dependencies and build
        run: |
          echo ${{vars.AWS_HOST_NAME}}@${{vars.AWS_HOST}}
          echo "${{secrets.AWS_PEM}}" > private_key 
          echo private_key 
          chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${{vars.AWS_HOST_NAME}}@${{vars.AWS_HOST}} '
              cd Full-Stack-Project-Assessment &&
              pwd &&
              git pull &&
              cd server &&
              npm install &&
              pm2 restart server.js
              '
