name: EC2 Deploy

on:
  push:
    branches:
      - "*"
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with: 
       ref: ${{github.ref}}
    - name: Create private key
      run: |
        mkdir ~/.ssh/
        echo "${{ secrets.MY_SECRET_SSH_KEY }}" > ~/.ssh/secretKey.pem
        chmod 400 ~/.ssh/secretKey.pem

    - name: Connect to EC2

      run: |
       ssh -i ~/.ssh/secretKey.pem -o StrictHostKeyChecking=no ubuntu@ec2-35-176-144-41.eu-west-2.compute.amazonaws.com 'cd ~/project/Full-Stack-Project-Assessment/server/ && git config pull.rebase true && git pull'
