
name: EC2 Deployment

on:
  push:
    branches: [ backup ]

jobs:
  deploy-to-ec2:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      AWS_REGION: eu-north-1
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: ${{ env.AWS_REGION }}
        role-to-assume: arn:aws:iam::058264451725:role/githutactionsECRAcess
        role-session-name: GitHubActionsSession

    - name: Log in to AWS ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build Docker image
      run: |
        ECR_REPOSITORY=058264451725.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/backend.docker
        IMAGE_TAG=latest
        docker build -t $ECR_REPOSITORY:$IMAGE_TAG .
      working-directory: ./server

    - name: Tag Docker image
      run: |
        ECR_REPOSITORY=058264451725.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/backend.docker
        IMAGE_TAG=latest
        docker tag $ECR_REPOSITORY:$IMAGE_TAG $ECR_REPOSITORY:$IMAGE_TAG
      working-directory: ./server

    - name: Push Docker image to ECR
      run: |
        ECR_REPOSITORY=058264451725.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/backend.docker
        IMAGE_TAG=latest
        docker push $ECR_REPOSITORY:$IMAGE_TAG
      working-directory: ./server

    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username:  ${{ secrets.EC2_SSH_USERNAME }}  
        key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        port: 22
        script: |
          sudo su - root <<'EOF'
          echo "Switching to root user to perform tasks"
          export ECR_REPOSITORY=058264451725.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/backend.docker
          export IMAGE_TAG=latest 
          aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin $ECR_REPOSITORY
          docker stop sharp_zhukovsky || true && docker rm sharp_zhukovsky || true
          docker run -d -p 5000:5000 \
            -e DB_NAME='${{ secrets.DB_NAME }}' \
            -e DB_HOST='${{ secrets.DB_HOST }}' \
            -e DB_PASSWORD='${{ secrets.DB_PASSWORD }}' \
            -e DB_PORT='${{ secrets.DB_PORT }}' \
            -e DB_USER='${{ secrets.DB_USER }}' \
            $ECR_REPOSITORY:$IMAGE_TAG
          EOF
