name: Push-to-EC2

# Trigger deployment only on push to Level--300 branch
on:
  push:
    branches:
      - Level--300

jobs:
  deploy:
    name: Deploy to EC2 on Level--300 branch push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy in EC2
        env:
            PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY}}
            HOST_NAME : ${{ secrets.HOST_DNS }}
            USERNAME : ${{ secrets.USERNAME  }}
        run: |
          echo "$PRIVATE_KEY" > video-key && chmod 600 video-key
          ssh -o StrictHostKeyChecking=no -i video-key -vvv ${USERNAME}@${HOST_NAME} bash sync.sh

       
