name: Backend deployments to EC2
on:
  push:
    branches:
      - main
    paths:
      - "server/**"
defaults:
  run:
    working-directory: ./server
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Add SSH key to agent
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > id_rsa_tmp
          chmod 600 id_rsa_tmp
          ssh-keygen -i id_rsa_tmp -f id_rsa
          rm id_rsa_tmp
      - name: SSH into EC2 instance and deploy 
        run: | 
          ssh -i id_rsa ubuntu@${{ secrets.EC2_DNS }} "bash -c 'cd /server.js && git pull && npm install && pm2 start server.js'"  

     