name: GCP Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'server/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to GCP
        uses: google-github-actions/auth@v1
        id: 'auth'
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - name: Deploy to App Engine
        uses: google-github-actions/deploy-appengine@v1.2.7
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          deliverables: app.yaml
          env_vars: ${{ secrets.GCP_ENV }}
          working_directory: server
      - name: Print to console
        run: echo "Deployed!"