name: CI Client Docker to S3

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t momahboobian/vr-client:latest ./client
          docker save -o vr-client.tar momahboobian/vr-client:latest
