name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to EC2
        run: |
          chmod 400 videorec-server-key.pem
          ssh -o StrictHostKeyChecking=no -i videorec-server-key.pem ec2-user@ec2-35-179-92-205.eu-west-2.compute.amazonaws.com 'bash -s' < deploy.sh
