name: test2

on:
  push:
    branches:
      - main
    paths:
      - "client/**"

defaults:
  run:
    working-directory: "client"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: create build
        run: npm run build
