name: Testing

on:
  pull_request:
    branches:
      - main

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - run: npm i
      - run: npm run build
