name: Deploy Backend to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH keys
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_PRIVATE_KEY }}

      - name: Deploy Backend
        run: |
          ssh -i ${{ secrets.EC2_PRIVATE_KEY }} ubuntu@3.11.9.16 'cd /home/ubuntu/server && git pull origin main && npm install && npm run build && pm2 restart server.js'
