name: Deploy Backend to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      EC2_HOST: ${{ secrets.EC2_HOST }}
      EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
      EC2_PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy Backend
      run: |
        scp -i ~/.ssh/private-key.pem -o StrictHostKeyChecking=no -r ./server $EC2_USERNAME@$EC2_HOST:/path/to/remote/server
