name: EC2 Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y openssh-client

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "$EC2_PRIVATE_KEY" > ~/.ssh/private-key.pem
          chmod 600 ~/.ssh/private-key.pem
          ssh-keyscan -t rsa $EC2_HOST >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          scp -i ~/.ssh/private-key.pem -o StrictHostKeyChecking=no -r "$LOCAL_BACKEND_PATH" "$EC2_USERNAME@$EC2_HOST:$REMOTE_BACKEND_PATH"
